### PR TITLE
Fix @fastify/session

### PR DESCRIPTION
**Pull request by mcollina**
This commits fixes the `@fastify/session` module that was broken due to the changes introduced in https://github.com/fastify/fastify-cookie/pull/237 (v9.0.0).

The problem is that the `onSend` hook installed by `@fastify/cookie` was firing before the `onSend` hook in `@fastify/session`, essentially not sending the cookie added by `@fastify/session`.

I added a tiny provision for this case.

### CODE REVIEW

**Comment by mcollina** [comment]
cc @gurgunday

**Review by Uzlopak — APPROVED** [review]
based on the unit test, LGTM

**Comment by gurgunday** [comment]
Oh I see, yeah lgtm too, but will just test something real fast

**Comment by gurgunday** [comment]
https://github.com/fastify/fastify-cookie/pull/241

Can you take a look?

**Pull request merged**
