### PR TITLE
Enable support for Fastify v2

### PR DESCRIPTION
**Pull request by cemremengu**

### CODE REVIEW

**Comment by hersman** [comment]
I was unable to use fastify-cookie without being on Fastify v2. I previously had Fastify v1.14.2, and I kept getting a null error on FastifyRequest.req at line 30 in plugin.js.

**Comment by mcollina** [comment]
What's your error? You likely need to use version 2.x of fastify-cookie.

**Comment by hersman** [comment]
Yes, but shouldn't the minimum version of Fastify be 2.0.0 in the value passed to fp() for your master branch?

**Comment by jsumners** [comment]
> Yes, but shouldn't the minimum version of Fastify be 2.0.0 in the value passed to fp() for your master branch?

Yes. A PR to fix would be most welcome.

**Comment by amkayondo** [comment]
I have got this error, anyway I can fix it **Error: fastify-plugin - expected '^1.0.0' fastify version, '2.8.0' is installed**

**Comment by jsumners** [comment]
Purge your dependencies and reinstall/update them. 

https://github.com/fastify/fastify-cookie/blob/72bf8e84db78b2e897c69fd286a69f07044d3031/plugin.js#L49

**Pull request merged**
