### PR TITLE
use named exports

### LINKED ISSUE #253: ESM imports are failing
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

N/A

### Plugin version

9.0.4

### Node.js version

19.9.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

13.2.1

### Description

Importing in ESM workspace is failing with an error:

```ts
import { fastifyCookie } from '@fastify/cookie';
         ^^^^^^^^^^^^^
SyntaxError: Named export 'fastifyCookie' not found. The requested module '@fastify/cookie' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@fastify/cookie';
const { fastifyCookie } = pkg;
```

### Steps to Reproduce

Add `"type": "module"` to `package.json`.

### Expected Behavior

Should work with ESM imports.

### PR DESCRIPTION
**Pull request by gurgunday**
Closes #253

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Uzlopak — CHANGES_REQUESTED** [review]
Why did you remove the signer exports?

**Comment by gurgunday** [comment]
All the previous way of `require`ing work:

```js
const { sign } = require("./plugin");
const { fastifyCookie } = require("./plugin");
const fastifyCookie2 = require("./plugin");

console.log(sign); // [Function: sign]
console.log(fastifyCookie.sign); // [Function: sign]
console.log(fastifyCookie2.sign); // [Function: sign]
```

**Comment by gurgunday** [comment]
All the previous way of `require`ing work:

```js
const { sign } = require("./plugin");
const { fastifyCookie } = require("./plugin");
const fastifyCookie2 = require("./plugin");

console.log(sign); // [Function: sign]
console.log(fastifyCookie.sign); // [Function: sign]
console.log(fastifyCookie2.sign); // [Function: sign]
```

**Review by Uzlopak — APPROVED** [review]
Ok. Too much circularity :D

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by gajus** [comment]
Thank you

**Pull request merged**
