### PR TITLE
Add npmignore to avoid publishing unnecessary files

### PR DESCRIPTION
**Pull request by kibertoad**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — COMMENTED** [review]
👎 

I don't like having to duplicate the work of `.gitignore`. Isn't the majority of this already covered there? Do we not need to simply add missing bits to `.gitignore`?

**Comment by kibertoad** [comment]
@jsumners .editorconfig and .github have to be committed, but we exclude them from publishing in main `fastify` repo, and it would make sense to do the same here.

**Comment by jsumners** [comment]
I'd really only care about things like `coverage/` being published in the npm package. `.editorconfig` and `.github` are fine in my opinion.

**Comment by kibertoad** [comment]
Closing, as other than everything that should be committed, everything is in gitignore already.

**Pull request closed without merging**
