### PR TITLE
ability to filter out requests / avoid setting cookie header

### PR DESCRIPTION
**Pull request by patrickmichalina**
Hi. Before I write the full spec I want to confirm something like this would be accepted

the idea is to support this syntax: 

```ts
{
      secure: true,
      path: '/',
      sameSite: 'strict',
      httpOnly: true,
      filter: (reply, name, value, options): boolean => {
        const cacheHeader = reply.getHeader('cache-control')
        return cacheHeader && cacheHeader.includes('public') ? true : false
}
```

I want to "filter" out requests to avoid setting the headers under certain cirumstances. In this example my filter checks response headers for `public` keyword and filters out those request from setting the `set-cookie` header. This particular example is useful for CDNs

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Normally filtering is expensive compared to do something only when needed. Can you please articulate why you can't just avoid to call `setCookie()` when you do not need it? Also why would you not create a new decorator that wrapped `reply.setCookie()` and apply that filtering?

**Comment by patrickmichalina** [comment]
@mcollina I am not calling `setCookie` myself directly. I am using `fastify-session` and unable to figure out how to STOP it from ALWAYS setting the cookie. I am open to recommendations here.

**Comment by patrickmichalina** [comment]
`Also why would you not create a new decorator that wrapped reply.setCookie() and apply that filtering?` Is there an example of this sort of approach?

**Comment by mcollina** [comment]
Can you please describe a bit your setup? Have you got some routes you need to send the cookies and some routes you don't?

**Comment by patrickmichalina** [comment]
@mcollina Sure. I am using fastify both as an API (json) and HTML renderer. There are some web pages pages that are `cache-control: private` and some pages that are `cache-control: public`. The entire domain sites behind a full site CDN. Using the cache-control headers is crucial to informing the proxy what is cacheable. We do not want to set-cookie when a route is public but it is fine to set when private. Hope this is enough to go on.

**Comment by Eomm** [comment]
> @mcollina I am not calling `setCookie` myself directly. I am using [fastify-session](https://github.com/SerayaEryn/fastify-session) and unable to figure out how to STOP it from ALWAYS setting the cookie. I am open to recommendations here.

It should be possible to write it like this:

```js
fastify.register((app, opts, next)=>{
  app.register(fastifyCookie);
  app.register(fastifySession, {secret: 'a secret with minimum length of 32 characters'});
  app.get('/private')
  next()
})

fastify.register((app, opts, next)=>{
  app.get('/public')
  next()
})
```

**Comment by patrickmichalina** [comment]
@Eomm Thanks. I saw this in another thread and it makes sense to me but I have not been able to reconcile this approach with NestJS. Have you done such a thing with NestJS + Fastify?

**Comment by jsumners** [comment]
@mcollina I'm not completely opposed to this, but it does seem like we already provide the functionality as @Eomm demonstrated. I know nothing of NestJS, though, so I would defer to people who know better.

**Comment by Eomm** [comment]
> @Eomm Thanks. I saw this in another thread and it makes sense to me but I have not been able to reconcile this approach with NestJS. Have you done such a thing with NestJS + Fastify?
> 
> In NestJS routes are declared like:
> 
> ```ts
> @Controller('/public')
> export class MyPublicController {
> 
> }
> ```

I don't use Nest, but if you could create a minimal repo with this issue as an example I would like to check it since NestJS is broadly used and it could be a good start 😆

**Pull request closed without merging**
