### PR TITLE
Use onRequest instead of preHandler

### PR DESCRIPTION
**Pull request by jsumners**
Now that Fastify v2 exists, we can hook in at the correct part of the lifecycle. This PR does that.

### CODE REVIEW

**Review by cemremengu — APPROVED** [review]
LGTM

**Comment by mcollina** [comment]
This change is semver-major.

**Review by mcollina — APPROVED** [review]
LGTM, even if I would be happier with a unit test

**Review by delvedor — APPROVED** [review]
LGTM

Agree with @mcollina on the additional unit test and the cut of a semver-major.

**Comment by jsumners** [comment]
It's unclear when I will be able to come back to this. Would anyone on the @fastify/core team be willing to carry this ball over the line? Sounds like a simple unit test would be necessary and then cutting a major release.

**Pull request merged**
