### PR TITLE
add secure: 'auto' Option

### PR DESCRIPTION
**Pull request by Uzlopak**
This functionality is basically taken from @fastify/session https://github.com/fastify/session/blob/b1fc11c6fbb16c63a1884f202fcd030ecdb18a07/lib/cookie.js#L17

On the long run, we can remove the cookie class from @fastify/session.
 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — CHANGES_REQUESTED** [review]
Can you document the option?

**Comment by Uzlopak** [comment]
@climba03003 
Done. I would rather copy paste the options from the cookie readme and modify it for our needs, but that means probably some licensing matters, so I just added a nothing explaining half sentence.

**Comment by climba03003** [comment]
> I would rather copy paste the options from the cookie readme and modify it for our needs, but that means probably some licensing matters, so I just added a nothing explaining half sentence.

What I request is actually document how `auto` should behave.
It is not transparent enough for the user decide to use `auto`.

I think it is suitable to explain in the format below.
```
+ `options.secure`: blablabla
```

**Review by climba03003 — APPROVED** [review]
LGTM. Thanks

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
